repository: dominickp/dominick.p.elu.so
title: Dom's Webzone
description: Leave a comment on this webzone if you want a pizza roll.
logo: ./img/dom.jpg
theme: jekyll-theme-minimal
# github: [metadata]
gems:
  - "jekyll-github-metadata"